package ir.kasra_sh.nanoserver.utils;

public class MimeTypes {

    public enum Application {
        ;
        public static String EZ = "application/andrew-inset";
        public static String AW = "application/applixware";
        public static String ATOM = "application/atom+xml";
        public static String ATOMCAT = "application/atomcat+xml";
        public static String ATOMSVC = "application/atomsvc+xml";
        public static String CCXML = "application/ccxml+xml";
        public static String CDMIA = "application/cdmi-capability";
        public static String CDMIC = "application/cdmi-container";
        public static String CDMID = "application/cdmi-domain";
        public static String CDMIO = "application/cdmi-object";
        public static String CDMIQ = "application/cdmi-queue";
        public static String CU = "application/cu-seeme";
        public static String DAVMOUNT = "application/davmount+xml";
        public static String DBK = "application/docbook+xml";
        public static String DSSC = "application/dssc+der";
        public static String XDSSC = "application/dssc+xml";
        public static String ECMA = "application/ecmascript";
        public static String EMMA = "application/emma+xml";
        public static String EPUB = "application/epub+zip";
        public static String EXI = "application/exi";
        public static String PFR = "application/font-tdpfr";
        public static String GML = "application/gml+xml";
        public static String GPX = "application/gpx+xml";
        public static String GXF = "application/gxf";
        public static String STK = "application/hyperstudio";
        public static String INK = "application/inkml+xml";
        public static String IPFIX = "application/ipfix";
        public static String JAR = "application/java-archive";
        public static String SER = "application/java-serialized-object";
        public static String CLASS = "application/java-vm";
        public static String JS = "application/javascript";
        public static String JSON = "application/json";
        public static String JSONML = "application/jsonml+json";
        public static String LOSTXML = "application/lost+xml";
        public static String HQX = "application/mac-binhex40";
        public static String CPT = "application/mac-compactpro";
        public static String MADS = "application/mads+xml";
        public static String MRC = "application/marc";
        public static String MRCX = "application/marcxml+xml";
        public static String MA = "application/mathematica";
        public static String MATHML = "application/mathml+xml";
        public static String MBOX = "application/mbox";
        public static String MSCML = "application/mediaservercontrol+xml";
        public static String METALINK = "application/metalink+xml";
        public static String META4 = "application/metalink4+xml";
        public static String METS = "application/mets+xml";
        public static String MODS = "application/mods+xml";
        public static String M21 = "application/mp21";
        public static String MP4S = "application/mp4";
        public static String DOC = "application/msword";
        public static String MXF = "application/mxf";
        public static String BIN = "application/octet-stream";
        public static String ODA = "application/oda";
        public static String OPF = "application/oebps-package+xml";
        public static String OGX = "application/ogg";
        public static String OMDOC = "application/omdoc+xml";
        public static String ONETOC = "application/onenote";
        public static String OXPS = "application/oxps";
        public static String XER = "application/patch-ops-error+xml";
        public static String PDF = "application/pdf";
        public static String PGP = "application/pgp-encrypted";
        public static String ASC = "application/pgp-signature";
        public static String PRF = "application/pics-rules";
        public static String P10 = "application/pkcs10";
        public static String P7M = "application/pkcs7-mime";
        public static String P7S = "application/pkcs7-signature";
        public static String P8 = "application/pkcs8";
        public static String AC = "application/pkix-attr-cert";
        public static String CER = "application/pkix-cert";
        public static String CRL = "application/pkix-crl";
        public static String PKIPATH = "application/pkix-pkipath";
        public static String PKI = "application/pkixcmp";
        public static String PLS = "application/pls+xml";
        public static String AI = "application/postscript";
        public static String CWW = "application/prs.cww";
        public static String PSKCXML = "application/pskc+xml";
        public static String RDF = "application/rdf+xml";
        public static String RIF = "application/reginfo+xml";
        public static String RNC = "application/relax-ng-compact-syntax";
        public static String RL = "application/resource-lists+xml";
        public static String RLD = "application/resource-lists-diff+xml";
        public static String RS = "application/rls-services+xml";
        public static String GBR = "application/rpki-ghostbusters";
        public static String MFT = "application/rpki-manifest";
        public static String ROA = "application/rpki-roa";
        public static String RSD = "application/rsd+xml";
        public static String RSS = "application/rss+xml";
        public static String RTF = "application/rtf";
        public static String SBML = "application/sbml+xml";
        public static String SCQ = "application/scvp-cv-request";
        public static String SCS = "application/scvp-cv-response";
        public static String SPQ = "application/scvp-vp-request";
        public static String SPP = "application/scvp-vp-response";
        public static String SDP = "application/sdp";
        public static String SETPAY = "application/set-payment-initiation";
        public static String SETREG = "application/set-registration-initiation";
        public static String SHF = "application/shf+xml";
        public static String SMI = "application/smil+xml";
        public static String RQ = "application/sparql-query";
        public static String SRX = "application/sparql-results+xml";
        public static String GRAM = "application/srgs";
        public static String GRXML = "application/srgs+xml";
        public static String SRU = "application/sru+xml";
        public static String SSDL = "application/ssdl+xml";
        public static String SSML = "application/ssml+xml";
        public static String TEI = "application/tei+xml";
        public static String TFI = "application/thraud+xml";
        public static String TSD = "application/timestamped-data";
        public static String PLB = "application/vnd.3gpp.pic-bw-large";
        public static String PSB = "application/vnd.3gpp.pic-bw-small";
        public static String PVB = "application/vnd.3gpp.pic-bw-var";
        public static String TCAP = "application/vnd.3gpp2.tcap";
        public static String PWN = "application/vnd.3m.post-it-notes";
        public static String ASO = "application/vnd.accpac.simply.aso";
        public static String IMP = "application/vnd.accpac.simply.imp";
        public static String ACU = "application/vnd.acucobol";
        public static String ATC = "application/vnd.acucorp";
        public static String AIR = "application/vnd.adobe.air-application-installer-package+zip";
        public static String FCDT = "application/vnd.adobe.formscentral.fcdt";
        public static String FXP = "application/vnd.adobe.fxp";
        public static String XDP = "application/vnd.adobe.xdp+xml";
        public static String XFDF = "application/vnd.adobe.xfdf";
        public static String AHEAD = "application/vnd.ahead.space";
        public static String AZF = "application/vnd.airzip.filesecure.azf";
        public static String AZS = "application/vnd.airzip.filesecure.azs";
        public static String AZW = "application/vnd.amazon.ebook";
        public static String ACC = "application/vnd.americandynamics.acc";
        public static String AMI = "application/vnd.amiga.ami";
        public static String APK = "application/vnd.android.package-archive";
        public static String CII = "application/vnd.anser-web-certificate-issue-initiation";
        public static String FTI = "application/vnd.anser-web-funds-transfer-initiation";
        public static String ATX = "application/vnd.antix.game-component";
        public static String MPKG = "application/vnd.apple.installer+xml";
        public static String M3U8 = "application/vnd.apple.mpegurl";
        public static String SWI = "application/vnd.aristanetworks.swi";
        public static String IOTA = "application/vnd.astraea-software.iota";
        public static String AEP = "application/vnd.audiograph";
        public static String MPM = "application/vnd.blueice.multipass";
        public static String BMI = "application/vnd.bmi";
        public static String REP = "application/vnd.businessobjects";
        public static String CDXML = "application/vnd.chemdraw+xml";
        public static String MMD = "application/vnd.chipnuts.karaoke-mmd";
        public static String CDY = "application/vnd.cinderella";
        public static String CLA = "application/vnd.claymore";
        public static String RP9 = "application/vnd.cloanto.rp9";
        public static String C4G = "application/vnd.clonk.c4group";
        public static String C11AMC = "application/vnd.cluetrust.cartomobile-config";
        public static String C11AMZ = "application/vnd.cluetrust.cartomobile-config-pkg";
        public static String CSP = "application/vnd.commonspace";
        public static String CDBCMSG = "application/vnd.contact.cmsg";
        public static String CMC = "application/vnd.cosmocaller";
        public static String CLKX = "application/vnd.crick.clicker";
        public static String CLKK = "application/vnd.crick.clicker.keyboard";
        public static String CLKP = "application/vnd.crick.clicker.palette";
        public static String CLKT = "application/vnd.crick.clicker.template";
        public static String CLKW = "application/vnd.crick.clicker.wordbank";
        public static String WBS = "application/vnd.criticaltools.wbs+xml";
        public static String PML = "application/vnd.ctc-posml";
        public static String PPD = "application/vnd.cups-ppd";
        public static String CAR = "application/vnd.curl.car";
        public static String PCURL = "application/vnd.curl.pcurl";
        public static String DART = "application/vnd.dart";
        public static String RDZ = "application/vnd.data-vision.rdz";
        public static String UVF = "application/vnd.dece.data";
        public static String UVT = "application/vnd.dece.ttml+xml";
        public static String UVX = "application/vnd.dece.unspecified";
        public static String UVZ = "application/vnd.dece.zip";
        public static String FE_LAUNCH = "application/vnd.denovo.fcselayout-link";
        public static String DNA = "application/vnd.dna";
        public static String MLP = "application/vnd.dolby.mlp";
        public static String DPG = "application/vnd.dpgraph";
        public static String DFAC = "application/vnd.dreamfactory";
        public static String KPXX = "application/vnd.ds-keypoint";
        public static String AIT = "application/vnd.dvb.ait";
        public static String SVC = "application/vnd.dvb.service";
        public static String GEO = "application/vnd.dynageo";
        public static String MAG = "application/vnd.ecowin.chart";
        public static String NML = "application/vnd.enliven";
        public static String ESF = "application/vnd.epson.esf";
        public static String MSF = "application/vnd.epson.msf";
        public static String QAM = "application/vnd.epson.quickanime";
        public static String SLT = "application/vnd.epson.salt";
        public static String SSF = "application/vnd.epson.ssf";
        public static String ES3 = "application/vnd.eszigno3+xml";
        public static String EZ2 = "application/vnd.ezpix-album";
        public static String EZ3 = "application/vnd.ezpix-package";
        public static String FDF = "application/vnd.fdf";
        public static String MSEED = "application/vnd.fdsn.mseed";
        public static String SEED = "application/vnd.fdsn.seed";
        public static String GPH = "application/vnd.flographit";
        public static String FTC = "application/vnd.fluxtime.clip";
        public static String FM = "application/vnd.framemaker";
        public static String FNC = "application/vnd.frogans.fnc";
        public static String LTF = "application/vnd.frogans.ltf";
        public static String FSC = "application/vnd.fsc.weblaunch";
        public static String OAS = "application/vnd.fujitsu.oasys";
        public static String OA2 = "application/vnd.fujitsu.oasys2";
        public static String OA3 = "application/vnd.fujitsu.oasys3";
        public static String FG5 = "application/vnd.fujitsu.oasysgp";
        public static String BH2 = "application/vnd.fujitsu.oasysprs";
        public static String DDD = "application/vnd.fujixerox.ddd";
        public static String XDW = "application/vnd.fujixerox.docuworks";
        public static String XBD = "application/vnd.fujixerox.docuworks.binder";
        public static String FZS = "application/vnd.fuzzysheet";
        public static String TXD = "application/vnd.genomatix.tuxedo";
        public static String GGB = "application/vnd.geogebra.file";
        public static String GGT = "application/vnd.geogebra.tool";
        public static String GEX = "application/vnd.geometry-explorer";
        public static String GXT = "application/vnd.geonext";
        public static String G2W = "application/vnd.geoplan";
        public static String G3W = "application/vnd.geospace";
        public static String GMX = "application/vnd.gmx";
        public static String KML = "application/vnd.google-earth.kml+xml";
        public static String KMZ = "application/vnd.google-earth.kmz";
        public static String GQF = "application/vnd.grafeq";
        public static String GAC = "application/vnd.groove-account";
        public static String GHF = "application/vnd.groove-help";
        public static String GIM = "application/vnd.groove-identity-message";
        public static String GRV = "application/vnd.groove-injector";
        public static String GTM = "application/vnd.groove-tool-message";
        public static String TPL = "application/vnd.groove-tool-template";
        public static String VCG = "application/vnd.groove-vcard";
        public static String HAL = "application/vnd.hal+xml";
        public static String ZMM = "application/vnd.handheld-entertainment+xml";
        public static String HBCI = "application/vnd.hbci";
        public static String LES = "application/vnd.hhe.lesson-player";
        public static String HPGL = "application/vnd.hp-hpgl";
        public static String HPID = "application/vnd.hp-hpid";
        public static String HPS = "application/vnd.hp-hps";
        public static String JLT = "application/vnd.hp-jlyt";
        public static String PCL = "application/vnd.hp-pcl";
        public static String PCLXL = "application/vnd.hp-pclxl";
        public static String SFD_HDSTX = "application/vnd.hydrostatix.sof-data";
        public static String MPY = "application/vnd.ibm.minipay";
        public static String AFP = "application/vnd.ibm.modcap";
        public static String IRM = "application/vnd.ibm.rights-management";
        public static String SC = "application/vnd.ibm.secure-container";
        public static String ICC = "application/vnd.iccprofile";
        public static String IGL = "application/vnd.igloader";
        public static String IVP = "application/vnd.immervision-ivp";
        public static String IVU = "application/vnd.immervision-ivu";
        public static String IGM = "application/vnd.insors.igm";
        public static String XPW = "application/vnd.intercon.formnet";
        public static String I2G = "application/vnd.intergeo";
        public static String QBO = "application/vnd.intu.qbo";
        public static String QFX = "application/vnd.intu.qfx";
        public static String RCPROFILE = "application/vnd.ipunplugged.rcprofile";
        public static String IRP = "application/vnd.irepository.package+xml";
        public static String XPR = "application/vnd.is-xpr";
        public static String FCS = "application/vnd.isac.fcs";
        public static String JAM = "application/vnd.jam";
        public static String RMS = "application/vnd.jcp.javame.midlet-rms";
        public static String JISP = "application/vnd.jisp";
        public static String JODA = "application/vnd.joost.joda-archive";
        public static String KTZ = "application/vnd.kahootz";
        public static String KARBON = "application/vnd.kde.karbon";
        public static String CHRT = "application/vnd.kde.kchart";
        public static String KFO = "application/vnd.kde.kformula";
        public static String FLW = "application/vnd.kde.kivio";
        public static String KON = "application/vnd.kde.kontour";
        public static String KPR = "application/vnd.kde.kpresenter";
        public static String KSP = "application/vnd.kde.kspread";
        public static String KWD = "application/vnd.kde.kword";
        public static String HTKE = "application/vnd.kenameaapp";
        public static String KIA = "application/vnd.kidspiration";
        public static String KNE = "application/vnd.kinar";
        public static String SKP = "application/vnd.koan";
        public static String SSE = "application/vnd.kodak-descriptor";
        public static String LASXML = "application/vnd.las.las+xml";
        public static String LBD = "application/vnd.llamagraphics.life-balance.desktop";
        public static String LBE = "application/vnd.llamagraphics.life-balance.exchange+xml";
        public static String _123 = "application/vnd.lotus-1-2-3";
        public static String APR = "application/vnd.lotus-approach";
        public static String PRE = "application/vnd.lotus-freelance";
        public static String NSF = "application/vnd.lotus-notes";
        public static String ORG = "application/vnd.lotus-organizer";
        public static String SCM = "application/vnd.lotus-screencam";
        public static String LWP = "application/vnd.lotus-wordpro";
        public static String PORTPKG = "application/vnd.macports.portpkg";
        public static String MCD = "application/vnd.mcd";
        public static String MC1 = "application/vnd.medcalcdata";
        public static String CDKEY = "application/vnd.mediastation.cdkey";
        public static String MWF = "application/vnd.mfer";
        public static String MFM = "application/vnd.mfmp";
        public static String FLO = "application/vnd.micrografx.flo";
        public static String IGX = "application/vnd.micrografx.igx";
        public static String MIF = "application/vnd.mif";
        public static String DAF = "application/vnd.mobius.daf";
        public static String DIS = "application/vnd.mobius.dis";
        public static String MBK = "application/vnd.mobius.mbk";
        public static String MQY = "application/vnd.mobius.mqy";
        public static String MSL = "application/vnd.mobius.msl";
        public static String PLC = "application/vnd.mobius.plc";
        public static String TXF = "application/vnd.mobius.txf";
        public static String MPN = "application/vnd.mophun.application";
        public static String MPC = "application/vnd.mophun.certificate";
        public static String XUL = "application/vnd.mozilla.xul+xml";
        public static String CIL = "application/vnd.ms-artgalry";
        public static String CAB = "application/vnd.ms-cab-compressed";
        public static String XLS = "application/vnd.ms-excel";
        public static String XLAM = "application/vnd.ms-excel.addin.macroenabled.12";
        public static String XLSB = "application/vnd.ms-excel.sheet.binary.macroenabled.12";
        public static String XLSM = "application/vnd.ms-excel.sheet.macroenabled.12";
        public static String XLTM = "application/vnd.ms-excel.template.macroenabled.12";
        public static String EOT = "application/vnd.ms-fontobject";
        public static String CHM = "application/vnd.ms-htmlhelp";
        public static String IMS = "application/vnd.ms-ims";
        public static String LRM = "application/vnd.ms-lrm";
        public static String THMX = "application/vnd.ms-officetheme";
        public static String CAT = "application/vnd.ms-pki.seccat";
        public static String STL = "application/vnd.ms-pki.stl";
        public static String PPT = "application/vnd.ms-powerpoint";
        public static String PPAM = "application/vnd.ms-powerpoint.addin.macroenabled.12";
        public static String PPTM = "application/vnd.ms-powerpoint.presentation.macroenabled.12";
        public static String SLDM = "application/vnd.ms-powerpoint.slide.macroenabled.12";
        public static String PPSM = "application/vnd.ms-powerpoint.slideshow.macroenabled.12";
        public static String POTM = "application/vnd.ms-powerpoint.template.macroenabled.12";
        public static String MPP = "application/vnd.ms-project";
        public static String DOCM = "application/vnd.ms-word.document.macroenabled.12";
        public static String DOTM = "application/vnd.ms-word.template.macroenabled.12";
        public static String WPS = "application/vnd.ms-works";
        public static String WPL = "application/vnd.ms-wpl";
        public static String XPS = "application/vnd.ms-xpsdocument";
        public static String MSEQ = "application/vnd.mseq";
        public static String MUS = "application/vnd.musician";
        public static String MSTY = "application/vnd.muvee.style";
        public static String TAGLET = "application/vnd.mynfc";
        public static String NLU = "application/vnd.neurolanguage.nlu";
        public static String NTF = "application/vnd.nitf";
        public static String NND = "application/vnd.noblenet-directory";
        public static String NNS = "application/vnd.noblenet-sealer";
        public static String NNW = "application/vnd.noblenet-web";
        public static String NGDAT = "application/vnd.nokia.n-gage.data";
        public static String NGAGE = "application/vnd.nokia.n-gage.symbian.install";
        public static String RPST = "application/vnd.nokia.radio-preset";
        public static String RPSS = "application/vnd.nokia.radio-presets";
        public static String EDM = "application/vnd.novadigm.edm";
        public static String EDX = "application/vnd.novadigm.edx";
        public static String EXT = "application/vnd.novadigm.ext";
        public static String ODC = "application/vnd.oasis.opendocument.chart";
        public static String OTC = "application/vnd.oasis.opendocument.chart-template";
        public static String ODB = "application/vnd.oasis.opendocument.database";
        public static String ODF = "application/vnd.oasis.opendocument.formula";
        public static String ODFT = "application/vnd.oasis.opendocument.formula-template";
        public static String ODG = "application/vnd.oasis.opendocument.graphics";
        public static String OTG = "application/vnd.oasis.opendocument.graphics-template";
        public static String ODI = "application/vnd.oasis.opendocument.image";
        public static String OTI = "application/vnd.oasis.opendocument.image-template";
        public static String ODP = "application/vnd.oasis.opendocument.presentation";
        public static String OTP = "application/vnd.oasis.opendocument.presentation-template";
        public static String ODS = "application/vnd.oasis.opendocument.spreadsheet";
        public static String OTS = "application/vnd.oasis.opendocument.spreadsheet-template";
        public static String ODT = "application/vnd.oasis.opendocument.text";
        public static String ODM = "application/vnd.oasis.opendocument.text-master";
        public static String OTT = "application/vnd.oasis.opendocument.text-template";
        public static String OTH = "application/vnd.oasis.opendocument.text-web";
        public static String XO = "application/vnd.olpc-sugar";
        public static String DD2 = "application/vnd.oma.dd2+xml";
        public static String OXT = "application/vnd.openofficeorg.extension";
        public static String PPTX = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        public static String SLDX = "application/vnd.openxmlformats-officedocument.presentationml.slide";
        public static String PPSX = "application/vnd.openxmlformats-officedocument.presentationml.slideshow";
        public static String POTX = "application/vnd.openxmlformats-officedocument.presentationml.template";
        public static String XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        public static String XLTX = "application/vnd.openxmlformats-officedocument.spreadsheetml.template";
        public static String DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
        public static String DOTX = "application/vnd.openxmlformats-officedocument.wordprocessingml.template";
        public static String MGP = "application/vnd.osgeo.mapguide.package";
        public static String DP = "application/vnd.osgi.dp";
        public static String ESA = "application/vnd.osgi.subsystem";
        public static String PDB = "application/vnd.palm";
        public static String PAW = "application/vnd.pawaafile";
        public static String STR = "application/vnd.pg.format";
        public static String EI6 = "application/vnd.pg.osasli";
        public static String EFIF = "application/vnd.picsel";
        public static String WG = "application/vnd.pmi.widget";
        public static String PLF = "application/vnd.pocketlearn";
        public static String PBD = "application/vnd.powerbuilder6";
        public static String BOX = "application/vnd.previewsystems.box";
        public static String MGZ = "application/vnd.proteus.magazine";
        public static String QPS = "application/vnd.publishare-delta-tree";
        public static String PTID = "application/vnd.pvi.ptid1";
        public static String QXD = "application/vnd.quark.quarkxpress";
        public static String BED = "application/vnd.realvnc.bed";
        public static String MXL = "application/vnd.recordare.musicxml";
        public static String MUSICXML = "application/vnd.recordare.musicxml+xml";
        public static String CRYPTONOTE = "application/vnd.rig.cryptonote";
        public static String COD = "application/vnd.rim.cod";
        public static String RM = "application/vnd.rn-realmedia";
        public static String RMVB = "application/vnd.rn-realmedia-vbr";
        public static String LINK66 = "application/vnd.route66.link66+xml";
        public static String ST = "application/vnd.sailingtracker.track";
        public static String SEE = "application/vnd.seemail";
        public static String SEMA = "application/vnd.sema";
        public static String SEMD = "application/vnd.semd";
        public static String SEMF = "application/vnd.semf";
        public static String IFM = "application/vnd.shana.informed.formdata";
        public static String ITP = "application/vnd.shana.informed.formtemplate";
        public static String IIF = "application/vnd.shana.informed.interchange";
        public static String IPK = "application/vnd.shana.informed.package";
        public static String TWD = "application/vnd.simtech-mindmapper";
        public static String MMF = "application/vnd.smaf";
        public static String TEACHER = "application/vnd.smart.teacher";
        public static String SDKM = "application/vnd.solent.sdkm+xml";
        public static String DXP = "application/vnd.spotfire.dxp";
        public static String SFS = "application/vnd.spotfire.sfs";
        public static String SDC = "application/vnd.stardivision.calc";
        public static String SDA = "application/vnd.stardivision.draw";
        public static String SDD = "application/vnd.stardivision.impress";
        public static String SMF = "application/vnd.stardivision.math";
        public static String SDW = "application/vnd.stardivision.writer";
        public static String SGL = "application/vnd.stardivision.writer-global";
        public static String SMZIP = "application/vnd.stepmania.package";
        public static String SM = "application/vnd.stepmania.stepchart";
        public static String SXC = "application/vnd.sun.xml.calc";
        public static String STC = "application/vnd.sun.xml.calc.template";
        public static String SXD = "application/vnd.sun.xml.draw";
        public static String STD = "application/vnd.sun.xml.draw.template";
        public static String SXI = "application/vnd.sun.xml.impress";
        public static String STI = "application/vnd.sun.xml.impress.template";
        public static String SXM = "application/vnd.sun.xml.math";
        public static String SXW = "application/vnd.sun.xml.writer";
        public static String SXG = "application/vnd.sun.xml.writer.global";
        public static String STW = "application/vnd.sun.xml.writer.template";
        public static String SUS = "application/vnd.sus-calendar";
        public static String SVD = "application/vnd.svd";
        public static String SIS = "application/vnd.symbian.install";
        public static String XSM = "application/vnd.syncml+xml";
        public static String BDM = "application/vnd.syncml.dm+wbxml";
        public static String XDM = "application/vnd.syncml.dm+xml";
        public static String TAO = "application/vnd.tao.intent-module-archive";
        public static String PCAP = "application/vnd.tcpdump.pcap";
        public static String TMO = "application/vnd.tmobile-livetv";
        public static String TPT = "application/vnd.trid.tpt";
        public static String MXS = "application/vnd.triscape.mxs";
        public static String TRA = "application/vnd.trueapp";
        public static String UFD = "application/vnd.ufdl";
        public static String UTZ = "application/vnd.uiq.theme";
        public static String UMJ = "application/vnd.umajin";
        public static String UNITYWEB = "application/vnd.unity";
        public static String UOML = "application/vnd.uoml+xml";
        public static String VCX = "application/vnd.vcx";
        public static String VSD = "application/vnd.visio";
        public static String VIS = "application/vnd.visionary";
        public static String VSF = "application/vnd.vsf";
        public static String WBXML = "application/vnd.wap.wbxml";
        public static String WMLC = "application/vnd.wap.wmlc";
        public static String WMLSC = "application/vnd.wap.wmlscriptc";
        public static String WTB = "application/vnd.webturbo";
        public static String NBP = "application/vnd.wolfram.player";
        public static String WPD = "application/vnd.wordperfect";
        public static String WQD = "application/vnd.wqd";
        public static String STF = "application/vnd.wt.stf";
        public static String XAR = "application/vnd.xara";
        public static String XFDL = "application/vnd.xfdl";
        public static String HVD = "application/vnd.yamaha.hv-dic";
        public static String HVS = "application/vnd.yamaha.hv-script";
        public static String HVP = "application/vnd.yamaha.hv-voice";
        public static String OSF = "application/vnd.yamaha.openscoreformat";
        public static String OSFPVG = "application/vnd.yamaha.openscoreformat.osfpvg+xml";
        public static String SAF = "application/vnd.yamaha.smaf-audio";
        public static String SPF = "application/vnd.yamaha.smaf-phrase";
        public static String CMP = "application/vnd.yellowriver-custom-menu";
        public static String ZIR = "application/vnd.zul";
        public static String ZAZ = "application/vnd.zzazz.deck+xml";
        public static String VXML = "application/voicexml+xml";
        public static String WGT = "application/widget";
        public static String HLP = "application/winhlp";
        public static String WSDL = "application/wsdl+xml";
        public static String WSPOLICY = "application/wspolicy+xml";
        public static String _7Z = "application/x-7z-compressed";
        public static String ABW = "application/x-abiword";
        public static String ACE = "application/x-ace-compressed";
        public static String DMG = "application/x-apple-diskimage";
        public static String AAB = "application/x-authorware-bin";
        public static String AAM = "application/x-authorware-map";
        public static String AAS = "application/x-authorware-seg";
        public static String BCPIO = "application/x-bcpio";
        public static String TORRENT = "application/x-bittorrent";
        public static String BLB = "application/x-blorb";
        public static String BZ = "application/x-bzip";
        public static String BZ2 = "application/x-bzip2";
        public static String CBR = "application/x-cbr";
        public static String VCD = "application/x-cdlink";
        public static String CFS = "application/x-cfs-compressed";
        public static String CHAT = "application/x-chat";
        public static String PGN = "application/x-chess-pgn";
        public static String NSC = "application/x-conference";
        public static String CPIO = "application/x-cpio";
        public static String CSH = "application/x-csh";
        public static String DEB = "application/x-debian-package";
        public static String DGC = "application/x-dgc-compressed";
        public static String DIR = "application/x-director";
        public static String WAD = "application/x-doom";
        public static String NCX = "application/x-dtbncx+xml";
        public static String DTB = "application/x-dtbook+xml";
        public static String RES = "application/x-dtbresource+xml";
        public static String DVI = "application/x-dvi";
        public static String EVY = "application/x-envoy";
        public static String EVA = "application/x-eva";
        public static String BDF = "application/x-font-bdf";
        public static String GSF = "application/x-font-ghostscript";
        public static String PSF = "application/x-font-linux-psf";
        public static String OTF = "application/x-font-otf";
        public static String PCF = "application/x-font-pcf";
        public static String SNF = "application/x-font-snf";
        public static String TTF = "application/x-font-ttf";
        public static String PFA = "application/x-font-type1";
        public static String WOFF = "application/font-woff";
        public static String ARC = "application/x-freearc";
        public static String SPL = "application/x-futuresplash";
        public static String GCA = "application/x-gca-compressed";
        public static String ULX = "application/x-glulx";
        public static String GNUMERIC = "application/x-gnumeric";
        public static String GRAMPS = "application/x-gramps-xml";
        public static String GTAR = "application/x-gtar";
        public static String HDF = "application/x-hdf";
        public static String INSTALL = "application/x-install-instructions";
        public static String ISO = "application/x-iso9660-image";
        public static String JNLP = "application/x-java-jnlp-file";
        public static String LATEX = "application/x-latex";
        public static String LZH = "application/x-lzh-compressed";
        public static String MIE = "application/x-mie";
        public static String PRC = "application/x-mobipocket-ebook";
        public static String APPLICATION = "application/x-ms-application";
        public static String LNK = "application/x-ms-shortcut";
        public static String WMD = "application/x-ms-wmd";
        public static String WMZ = "application/x-ms-wmz";
        public static String XBAP = "application/x-ms-xbap";
        public static String MDB = "application/x-msaccess";
        public static String OBD = "application/x-msbinder";
        public static String CRD = "application/x-mscardfile";
        public static String CLP = "application/x-msclip";
        public static String EXE = "application/x-msdownload";
        public static String MVB = "application/x-msmediaview";
        public static String WMF = "application/x-msmetafile";
        public static String MNY = "application/x-msmoney";
        public static String PUB = "application/x-mspublisher";
        public static String SCD = "application/x-msschedule";
        public static String TRM = "application/x-msterminal";
        public static String WRI = "application/x-mswrite";
        public static String NC = "application/x-netcdf";
        public static String NZB = "application/x-nzb";
        public static String P12 = "application/x-pkcs12";
        public static String P7B = "application/x-pkcs7-certificates";
        public static String P7R = "application/x-pkcs7-certreqresp";
        public static String RAR = "application/x-rar-compressed";
        public static String RIS = "application/x-research-info-systems";
        public static String SH = "application/x-sh";
        public static String SHAR = "application/x-shar";
        public static String SWF = "application/x-shockwave-flash";
        public static String XAP = "application/x-silverlight-app";
        public static String SQL = "application/x-sql";
        public static String SIT = "application/x-stuffit";
        public static String SITX = "application/x-stuffitx";
        public static String SRT = "application/x-subrip";
        public static String SV4CPIO = "application/x-sv4cpio";
        public static String SV4CRC = "application/x-sv4crc";
        public static String T3 = "application/x-t3vm-image";
        public static String GAM = "application/x-tads";
        public static String TAR = "application/x-tar";
        public static String TCL = "application/x-tcl";
        public static String TEX = "application/x-tex";
        public static String TFM = "application/x-tex-tfm";
        public static String TEXINFO = "application/x-texinfo";
        public static String OBJ = "application/x-tgif";
        public static String USTAR = "application/x-ustar";
        public static String SRC = "application/x-wais-source";
        public static String DER = "application/x-x509-ca-cert";
        public static String FIG = "application/x-xfig";
        public static String XLF = "application/x-xliff+xml";
        public static String XPI = "application/x-xpinstall";
        public static String XZ = "application/x-xz";
        public static String Z1 = "application/x-zmachine";
        public static String XAML = "application/xaml+xml";
        public static String XDF = "application/xcap-diff+xml";
        public static String XENC = "application/xenc+xml";
        public static String XHTML = "application/xhtml+xml";
        public static String XML = "application/xml";
        public static String DTD = "application/xml-dtd";
        public static String XOP = "application/xop+xml";
        public static String XPL = "application/xproc+xml";
        public static String XSLT = "application/xslt+xml";
        public static String XSPF = "application/xspf+xml";
        public static String MXML = "application/xv+xml";
        public static String YANG = "application/yang";
        public static String YIN = "application/yin+xml";
        public static String ZIP = "application/zip";
    }
    public enum Audio {
        ;
        public static String ADP = "audio/adpcm";
        public static String AU = "audio/basic";
        public static String MID = "audio/midi";
        public static String MP4A = "audio/mp4";
        public static String MP3 = "audio/mp3";
        public static String MPGA = "audio/mpeg";
        public static String OGA = "audio/ogg";
        public static String S3M = "audio/s3m";
        public static String SIL = "audio/silk";
        public static String UVA = "audio/vnd.dece.audio";
        public static String EOL = "audio/vnd.digital-winds";
        public static String DRA = "audio/vnd.dra";
        public static String DTS = "audio/vnd.dts";
        public static String DTSHD = "audio/vnd.dts.hd";
        public static String LVP = "audio/vnd.lucent.voice";
        public static String PYA = "audio/vnd.ms-playready.media.pya";
        public static String ECELP4800 = "audio/vnd.nuera.ecelp4800";
        public static String ECELP7470 = "audio/vnd.nuera.ecelp7470";
        public static String ECELP9600 = "audio/vnd.nuera.ecelp9600";
        public static String RIP = "audio/vnd.rip";
        public static String WEBA = "audio/webm";
        public static String AAC = "audio/x-aac";
        public static String AIF = "audio/x-aiff";
        public static String CAF = "audio/x-caf";
        public static String FLAC = "audio/x-flac";
        public static String MKA = "audio/x-matroska";
        public static String M3U = "audio/x-mpegurl";
        public static String WAX = "audio/x-ms-wax";
        public static String WMA = "audio/x-ms-wma";
        public static String RAM = "audio/x-pn-realaudio";
        public static String RMP = "audio/x-pn-realaudio-plugin";
        public static String WAV = "audio/x-wav";
        public static String XM = "audio/xm";
    }
    public enum Chemical {
        ;
        public static String CDX = "chemical/x-cdx";
        public static String CIF = "chemical/x-cif";
        public static String CMDF = "chemical/x-cmdf";
        public static String CML = "chemical/x-cml";
        public static String CSML = "chemical/x-csml";
        public static String XYZ = "chemical/x-xyz";
    }
    public enum Image {
        ;
        public static String BMP = "image/bmp";
        public static String CGM = "image/cgm";
        public static String G3 = "image/g3fax";
        public static String GIF = "image/gif";
        public static String IEF = "image/ief";
        public static String JPEG = "image/jpeg";
        public static String KTX = "image/ktx";
        public static String PNG = "image/png";
        public static String BTIF = "image/prs.btif";
        public static String SGI = "image/sgi";
        public static String SVG = "image/svg+xml";
        public static String TIFF = "image/tiff";
        public static String PSD = "image/vnd.adobe.photoshop";
        public static String UVI = "image/vnd.dece.graphic";
        public static String DJVU = "image/vnd.djvu";
        public static String DWG = "image/vnd.dwg";
        public static String DXF = "image/vnd.dxf";
        public static String FBS = "image/vnd.fastbidsheet";
        public static String FPX = "image/vnd.fpx";
        public static String FST = "image/vnd.fst";
        public static String MMR = "image/vnd.fujixerox.edmics-mmr";
        public static String RLC = "image/vnd.fujixerox.edmics-rlc";
        public static String MDI = "image/vnd.ms-modi";
        public static String WDP = "image/vnd.ms-photo";
        public static String NPX = "image/vnd.net-fpx";
        public static String WBMP = "image/vnd.wap.wbmp";
        public static String XIF = "image/vnd.xiff";
        public static String WEBP = "image/webp";
        public static String _3DS = "image/x-3ds";
        public static String RAS = "image/x-cmu-raster";
        public static String CMX = "image/x-cmx";
        public static String FH = "image/x-freehand";
        public static String ICO = "image/x-icon";
        public static String SID = "image/x-mrsid-image";
        public static String PCX = "image/x-pcx";
        public static String PIC = "image/x-pict";
        public static String PNM = "image/x-portable-anymap";
        public static String PBM = "image/x-portable-bitmap";
        public static String PGM = "image/x-portable-graymap";
        public static String PPM = "image/x-portable-pixmap";
        public static String RGB = "image/x-rgb";
        public static String TGA = "image/x-tga";
        public static String XBM = "image/x-xbitmap";
        public static String XPM = "image/x-xpixmap";
        public static String XWD = "image/x-xwindowdump";
    }
    public enum Message {
        ;
        public static String EML = "message/rfc822";
    }
    public enum Model {
        ;
        public static String IGS = "model/iges";
        public static String MSH = "model/mesh";
        public static String DAE = "model/vnd.collada+xml";
        public static String DWF = "model/vnd.dwf";
        public static String GDL = "model/vnd.gdl";
        public static String GTW = "model/vnd.gtw";
        public static String MTS = "model/vnd.mts";
        public static String VTU = "model/vnd.vtu";
        public static String WRL = "model/vrml";
        public static String X3DB = "model/x3d+binary";
        public static String X3DV = "model/x3d+vrml";
        public static String X3D = "model/x3d+xml";
    }
    public enum Text {
        ;
        public static String APPCACHE = "text/cache-manifest";
        public static String ICS = "text/calendar";
        public static String CSS = "text/css";
        public static String CSV = "text/csv";
        public static String HTML = "text/html";
        public static String N3 = "text/n3";
        public static String TXT = "text/plain";
        public static String DSC = "text/prs.lines.tag";
        public static String RTX = "text/richtext";
        public static String SGML = "text/sgml";
        public static String TSV = "text/tab-separated-values";
        public static String T = "text/troff";
        public static String TTL = "text/turtle";
        public static String URI = "text/uri-list";
        public static String VCARD = "text/vcard";
        public static String CURL = "text/vnd.curl";
        public static String DCURL = "text/vnd.curl.dcurl";
        public static String SCURL = "text/vnd.curl.scurl";
        public static String MCURL = "text/vnd.curl.mcurl";
        public static String SUB = "text/vnd.dvb.subtitle";
        public static String FLY = "text/vnd.fly";
        public static String FLX = "text/vnd.fmi.flexstor";
        public static String GV = "text/vnd.graphviz";
        public static String _3DML = "text/vnd.in3d.3dml";
        public static String SPOT = "text/vnd.in3d.spot";
        public static String JAD = "text/vnd.sun.j2me.app-descriptor";
        public static String WML = "text/vnd.wap.wml";
        public static String WMLS = "text/vnd.wap.wmlscript";
        public static String S = "text/x-asm";
        public static String C = "text/x-c";
        public static String F = "text/x-fortran";
        public static String JAVA = "text/x-java-source";
        public static String OPML = "text/x-opml";
        public static String P = "text/x-pascal";
        public static String NFO = "text/x-nfo";
        public static String ETX = "text/x-setext";
        public static String SFV = "text/x-sfv";
        public static String UU = "text/x-uuencode";
        public static String VCS = "text/x-vcalendar";
        public static String VCF = "text/x-vcard";
    }
    public enum Video {
        ;
        public static String _3GP = "video/3gpp";
        public static String _3G2 = "video/3gpp2";
        public static String H261 = "video/h261";
        public static String H263 = "video/h263";
        public static String H264 = "video/h264";
        public static String JPGV = "video/jpeg";
        public static String JPM = "video/jpm";
        public static String MJ2 = "video/mj2";
        public static String MP4 = "video/mp4";
        public static String MPEG = "video/mpeg";
        public static String OGV = "video/ogg";
        public static String QT = "video/quicktime";
        public static String UVH = "video/vnd.dece.hd";
        public static String UVM = "video/vnd.dece.mobile";
        public static String UVP = "video/vnd.dece.pd";
        public static String UVS = "video/vnd.dece.sd";
        public static String UVV = "video/vnd.dece.video";
        public static String DVB = "video/vnd.dvb.file";
        public static String FVT = "video/vnd.fvt";
        public static String MXU = "video/vnd.mpegurl";
        public static String PYV = "video/vnd.ms-playready.media.pyv";
        public static String UVU = "video/vnd.uvvu.mp4";
        public static String VIV = "video/vnd.vivo";
        public static String WEBM = "video/webm";
        public static String F4V = "video/x-f4v";
        public static String FLI = "video/x-fli";
        public static String FLV = "video/x-flv";
        public static String M4V = "video/x-m4v";
        public static String MKV = "video/x-matroska";
        public static String MNG = "video/x-mng";
        public static String ASF = "video/x-ms-asf";
        public static String VOB = "video/x-ms-vob";
        public static String WM = "video/x-ms-wm";
        public static String WMV = "video/x-ms-wmv";
        public static String WMX = "video/x-ms-wmx";
        public static String WVX = "video/x-ms-wvx";
        public static String AVI = "video/x-msvideo";
        public static String MOVIE = "video/x-sgi-movie";
        public static String SMV = "video/x-smv";
    }


    public static String byExt(String e){
        e = e.toUpperCase();
        switch(e) {
            case "EZ": return Application.EZ;
            case "AW": return Application.AW;
            case "ATOM": return Application.ATOM;
            case "ATOMCAT": return Application.ATOMCAT;
            case "ATOMSVC": return Application.ATOMSVC;
            case "CCXML": return Application.CCXML;
            case "CDMIA": return Application.CDMIA;
            case "CDMIC": return Application.CDMIC;
            case "CDMID": return Application.CDMID;
            case "CDMIO": return Application.CDMIO;
            case "CDMIQ": return Application.CDMIQ;
            case "CU": return Application.CU;
            case "DAVMOUNT": return Application.DAVMOUNT;
            case "DBK": return Application.DBK;
            case "DSSC": return Application.DSSC;
            case "XDSSC": return Application.XDSSC;
            case "ECMA": return Application.ECMA;
            case "EMMA": return Application.EMMA;
            case "EPUB": return Application.EPUB;
            case "EXI": return Application.EXI;
            case "PFR": return Application.PFR;
            case "GML": return Application.GML;
            case "GPX": return Application.GPX;
            case "GXF": return Application.GXF;
            case "STK": return Application.STK;
            case "INK": return Application.INK;
            case "IPFIX": return Application.IPFIX;
            case "JAR": return Application.JAR;
            case "SER": return Application.SER;
            case "CLASS": return Application.CLASS;
            case "JS": return Application.JS;
            case "JSON": return Application.JSON;
            case "JSONML": return Application.JSONML;
            case "LOSTXML": return Application.LOSTXML;
            case "HQX": return Application.HQX;
            case "CPT": return Application.CPT;
            case "MADS": return Application.MADS;
            case "MRC": return Application.MRC;
            case "MRCX": return Application.MRCX;
            case "MA": return Application.MA;
            case "MATHML": return Application.MATHML;
            case "MBOX": return Application.MBOX;
            case "MSCML": return Application.MSCML;
            case "METALINK": return Application.METALINK;
            case "META4": return Application.META4;
            case "METS": return Application.METS;
            case "MODS": return Application.MODS;
            case "M21": return Application.M21;
            case "MP4S": return Application.MP4S;
            case "DOC": return Application.DOC;
            case "MXF": return Application.MXF;
            case "BIN": return Application.BIN;
            case "ODA": return Application.ODA;
            case "OPF": return Application.OPF;
            case "OGX": return Application.OGX;
            case "OMDOC": return Application.OMDOC;
            case "ONETOC": return Application.ONETOC;
            case "OXPS": return Application.OXPS;
            case "XER": return Application.XER;
            case "PDF": return Application.PDF;
            case "PGP": return Application.PGP;
            case "ASC": return Application.ASC;
            case "PRF": return Application.PRF;
            case "P10": return Application.P10;
            case "P7M": return Application.P7M;
            case "P7S": return Application.P7S;
            case "P8": return Application.P8;
            case "AC": return Application.AC;
            case "CER": return Application.CER;
            case "CRL": return Application.CRL;
            case "PKIPATH": return Application.PKIPATH;
            case "PKI": return Application.PKI;
            case "PLS": return Application.PLS;
            case "AI": return Application.AI;
            case "CWW": return Application.CWW;
            case "PSKCXML": return Application.PSKCXML;
            case "RDF": return Application.RDF;
            case "RIF": return Application.RIF;
            case "RNC": return Application.RNC;
            case "RL": return Application.RL;
            case "RLD": return Application.RLD;
            case "RS": return Application.RS;
            case "GBR": return Application.GBR;
            case "MFT": return Application.MFT;
            case "ROA": return Application.ROA;
            case "RSD": return Application.RSD;
            case "RSS": return Application.RSS;
            case "RTF": return Application.RTF;
            case "SBML": return Application.SBML;
            case "SCQ": return Application.SCQ;
            case "SCS": return Application.SCS;
            case "SPQ": return Application.SPQ;
            case "SPP": return Application.SPP;
            case "SDP": return Application.SDP;
            case "SETPAY": return Application.SETPAY;
            case "SETREG": return Application.SETREG;
            case "SHF": return Application.SHF;
            case "SMI": return Application.SMI;
            case "RQ": return Application.RQ;
            case "SRX": return Application.SRX;
            case "GRAM": return Application.GRAM;
            case "GRXML": return Application.GRXML;
            case "SRU": return Application.SRU;
            case "SSDL": return Application.SSDL;
            case "SSML": return Application.SSML;
            case "TEI": return Application.TEI;
            case "TFI": return Application.TFI;
            case "TSD": return Application.TSD;
            case "PLB": return Application.PLB;
            case "PSB": return Application.PSB;
            case "PVB": return Application.PVB;
            case "TCAP": return Application.TCAP;
            case "PWN": return Application.PWN;
            case "ASO": return Application.ASO;
            case "IMP": return Application.IMP;
            case "ACU": return Application.ACU;
            case "ATC": return Application.ATC;
            case "AIR": return Application.AIR;
            case "FCDT": return Application.FCDT;
            case "FXP": return Application.FXP;
            case "XDP": return Application.XDP;
            case "XFDF": return Application.XFDF;
            case "AHEAD": return Application.AHEAD;
            case "AZF": return Application.AZF;
            case "AZS": return Application.AZS;
            case "AZW": return Application.AZW;
            case "ACC": return Application.ACC;
            case "AMI": return Application.AMI;
            case "APK": return Application.APK;
            case "CII": return Application.CII;
            case "FTI": return Application.FTI;
            case "ATX": return Application.ATX;
            case "MPKG": return Application.MPKG;
            case "M3U8": return Application.M3U8;
            case "SWI": return Application.SWI;
            case "IOTA": return Application.IOTA;
            case "AEP": return Application.AEP;
            case "MPM": return Application.MPM;
            case "BMI": return Application.BMI;
            case "REP": return Application.REP;
            case "CDXML": return Application.CDXML;
            case "MMD": return Application.MMD;
            case "CDY": return Application.CDY;
            case "CLA": return Application.CLA;
            case "RP9": return Application.RP9;
            case "C4G": return Application.C4G;
            case "C11AMC": return Application.C11AMC;
            case "C11AMZ": return Application.C11AMZ;
            case "CSP": return Application.CSP;
            case "CDBCMSG": return Application.CDBCMSG;
            case "CMC": return Application.CMC;
            case "CLKX": return Application.CLKX;
            case "CLKK": return Application.CLKK;
            case "CLKP": return Application.CLKP;
            case "CLKT": return Application.CLKT;
            case "CLKW": return Application.CLKW;
            case "WBS": return Application.WBS;
            case "PML": return Application.PML;
            case "PPD": return Application.PPD;
            case "CAR": return Application.CAR;
            case "PCURL": return Application.PCURL;
            case "DART": return Application.DART;
            case "RDZ": return Application.RDZ;
            case "UVF": return Application.UVF;
            case "UVT": return Application.UVT;
            case "UVX": return Application.UVX;
            case "UVZ": return Application.UVZ;
            case "FE_LAUNCH": return Application.FE_LAUNCH;
            case "DNA": return Application.DNA;
            case "MLP": return Application.MLP;
            case "DPG": return Application.DPG;
            case "DFAC": return Application.DFAC;
            case "KPXX": return Application.KPXX;
            case "AIT": return Application.AIT;
            case "SVC": return Application.SVC;
            case "GEO": return Application.GEO;
            case "MAG": return Application.MAG;
            case "NML": return Application.NML;
            case "ESF": return Application.ESF;
            case "MSF": return Application.MSF;
            case "QAM": return Application.QAM;
            case "SLT": return Application.SLT;
            case "SSF": return Application.SSF;
            case "ES3": return Application.ES3;
            case "EZ2": return Application.EZ2;
            case "EZ3": return Application.EZ3;
            case "FDF": return Application.FDF;
            case "MSEED": return Application.MSEED;
            case "SEED": return Application.SEED;
            case "GPH": return Application.GPH;
            case "FTC": return Application.FTC;
            case "FM": return Application.FM;
            case "FNC": return Application.FNC;
            case "LTF": return Application.LTF;
            case "FSC": return Application.FSC;
            case "OAS": return Application.OAS;
            case "OA2": return Application.OA2;
            case "OA3": return Application.OA3;
            case "FG5": return Application.FG5;
            case "BH2": return Application.BH2;
            case "DDD": return Application.DDD;
            case "XDW": return Application.XDW;
            case "XBD": return Application.XBD;
            case "FZS": return Application.FZS;
            case "TXD": return Application.TXD;
            case "GGB": return Application.GGB;
            case "GGT": return Application.GGT;
            case "GEX": return Application.GEX;
            case "GXT": return Application.GXT;
            case "G2W": return Application.G2W;
            case "G3W": return Application.G3W;
            case "GMX": return Application.GMX;
            case "KML": return Application.KML;
            case "KMZ": return Application.KMZ;
            case "GQF": return Application.GQF;
            case "GAC": return Application.GAC;
            case "GHF": return Application.GHF;
            case "GIM": return Application.GIM;
            case "GRV": return Application.GRV;
            case "GTM": return Application.GTM;
            case "TPL": return Application.TPL;
            case "VCG": return Application.VCG;
            case "HAL": return Application.HAL;
            case "ZMM": return Application.ZMM;
            case "HBCI": return Application.HBCI;
            case "LES": return Application.LES;
            case "HPGL": return Application.HPGL;
            case "HPID": return Application.HPID;
            case "HPS": return Application.HPS;
            case "JLT": return Application.JLT;
            case "PCL": return Application.PCL;
            case "PCLXL": return Application.PCLXL;
            case "SFD-HDSTX": return Application.SFD_HDSTX;
            case "MPY": return Application.MPY;
            case "AFP": return Application.AFP;
            case "IRM": return Application.IRM;
            case "SC": return Application.SC;
            case "ICC": return Application.ICC;
            case "IGL": return Application.IGL;
            case "IVP": return Application.IVP;
            case "IVU": return Application.IVU;
            case "IGM": return Application.IGM;
            case "XPW": return Application.XPW;
            case "I2G": return Application.I2G;
            case "QBO": return Application.QBO;
            case "QFX": return Application.QFX;
            case "RCPROFILE": return Application.RCPROFILE;
            case "IRP": return Application.IRP;
            case "XPR": return Application.XPR;
            case "FCS": return Application.FCS;
            case "JAM": return Application.JAM;
            case "RMS": return Application.RMS;
            case "JISP": return Application.JISP;
            case "JODA": return Application.JODA;
            case "KTZ": return Application.KTZ;
            case "KARBON": return Application.KARBON;
            case "CHRT": return Application.CHRT;
            case "KFO": return Application.KFO;
            case "FLW": return Application.FLW;
            case "KON": return Application.KON;
            case "KPR": return Application.KPR;
            case "KSP": return Application.KSP;
            case "KWD": return Application.KWD;
            case "HTKE": return Application.HTKE;
            case "KIA": return Application.KIA;
            case "KNE": return Application.KNE;
            case "SKP": return Application.SKP;
            case "SSE": return Application.SSE;
            case "LASXML": return Application.LASXML;
            case "LBD": return Application.LBD;
            case "LBE": return Application.LBE;
            case "123": return Application._123;
            case "APR": return Application.APR;
            case "PRE": return Application.PRE;
            case "NSF": return Application.NSF;
            case "ORG": return Application.ORG;
            case "SCM": return Application.SCM;
            case "LWP": return Application.LWP;
            case "PORTPKG": return Application.PORTPKG;
            case "MCD": return Application.MCD;
            case "MC1": return Application.MC1;
            case "CDKEY": return Application.CDKEY;
            case "MWF": return Application.MWF;
            case "MFM": return Application.MFM;
            case "FLO": return Application.FLO;
            case "IGX": return Application.IGX;
            case "MIF": return Application.MIF;
            case "DAF": return Application.DAF;
            case "DIS": return Application.DIS;
            case "MBK": return Application.MBK;
            case "MQY": return Application.MQY;
            case "MSL": return Application.MSL;
            case "PLC": return Application.PLC;
            case "TXF": return Application.TXF;
            case "MPN": return Application.MPN;
            case "MPC": return Application.MPC;
            case "XUL": return Application.XUL;
            case "CIL": return Application.CIL;
            case "CAB": return Application.CAB;
            case "XLS": return Application.XLS;
            case "XLAM": return Application.XLAM;
            case "XLSB": return Application.XLSB;
            case "XLSM": return Application.XLSM;
            case "XLTM": return Application.XLTM;
            case "EOT": return Application.EOT;
            case "CHM": return Application.CHM;
            case "IMS": return Application.IMS;
            case "LRM": return Application.LRM;
            case "THMX": return Application.THMX;
            case "CAT": return Application.CAT;
            case "STL": return Application.STL;
            case "PPT": return Application.PPT;
            case "PPAM": return Application.PPAM;
            case "PPTM": return Application.PPTM;
            case "SLDM": return Application.SLDM;
            case "PPSM": return Application.PPSM;
            case "POTM": return Application.POTM;
            case "MPP": return Application.MPP;
            case "DOCM": return Application.DOCM;
            case "DOTM": return Application.DOTM;
            case "WPS": return Application.WPS;
            case "WPL": return Application.WPL;
            case "XPS": return Application.XPS;
            case "MSEQ": return Application.MSEQ;
            case "MUS": return Application.MUS;
            case "MSTY": return Application.MSTY;
            case "TAGLET": return Application.TAGLET;
            case "NLU": return Application.NLU;
            case "NTF": return Application.NTF;
            case "NND": return Application.NND;
            case "NNS": return Application.NNS;
            case "NNW": return Application.NNW;
            case "NGDAT": return Application.NGDAT;
            case "N-GAGE": return Application.NGAGE;
            case "RPST": return Application.RPST;
            case "RPSS": return Application.RPSS;
            case "EDM": return Application.EDM;
            case "EDX": return Application.EDX;
            case "EXT": return Application.EXT;
            case "ODC": return Application.ODC;
            case "OTC": return Application.OTC;
            case "ODB": return Application.ODB;
            case "ODF": return Application.ODF;
            case "ODFT": return Application.ODFT;
            case "ODG": return Application.ODG;
            case "OTG": return Application.OTG;
            case "ODI": return Application.ODI;
            case "OTI": return Application.OTI;
            case "ODP": return Application.ODP;
            case "OTP": return Application.OTP;
            case "ODS": return Application.ODS;
            case "OTS": return Application.OTS;
            case "ODT": return Application.ODT;
            case "ODM": return Application.ODM;
            case "OTT": return Application.OTT;
            case "OTH": return Application.OTH;
            case "XO": return Application.XO;
            case "DD2": return Application.DD2;
            case "OXT": return Application.OXT;
            case "PPTX": return Application.PPTX;
            case "SLDX": return Application.SLDX;
            case "PPSX": return Application.PPSX;
            case "POTX": return Application.POTX;
            case "XLSX": return Application.XLSX;
            case "XLTX": return Application.XLTX;
            case "DOCX": return Application.DOCX;
            case "DOTX": return Application.DOTX;
            case "MGP": return Application.MGP;
            case "DP": return Application.DP;
            case "ESA": return Application.ESA;
            case "PDB": return Application.PDB;
            case "PAW": return Application.PAW;
            case "STR": return Application.STR;
            case "EI6": return Application.EI6;
            case "EFIF": return Application.EFIF;
            case "WG": return Application.WG;
            case "PLF": return Application.PLF;
            case "PBD": return Application.PBD;
            case "BOX": return Application.BOX;
            case "MGZ": return Application.MGZ;
            case "QPS": return Application.QPS;
            case "PTID": return Application.PTID;
            case "QXD": return Application.QXD;
            case "BED": return Application.BED;
            case "MXL": return Application.MXL;
            case "MUSICXML": return Application.MUSICXML;
            case "CRYPTONOTE": return Application.CRYPTONOTE;
            case "COD": return Application.COD;
            case "RM": return Application.RM;
            case "RMVB": return Application.RMVB;
            case "LINK66": return Application.LINK66;
            case "ST": return Application.ST;
            case "SEE": return Application.SEE;
            case "SEMA": return Application.SEMA;
            case "SEMD": return Application.SEMD;
            case "SEMF": return Application.SEMF;
            case "IFM": return Application.IFM;
            case "ITP": return Application.ITP;
            case "IIF": return Application.IIF;
            case "IPK": return Application.IPK;
            case "TWD": return Application.TWD;
            case "MMF": return Application.MMF;
            case "TEACHER": return Application.TEACHER;
            case "SDKM": return Application.SDKM;
            case "DXP": return Application.DXP;
            case "SFS": return Application.SFS;
            case "SDC": return Application.SDC;
            case "SDA": return Application.SDA;
            case "SDD": return Application.SDD;
            case "SMF": return Application.SMF;
            case "SDW": return Application.SDW;
            case "SGL": return Application.SGL;
            case "SMZIP": return Application.SMZIP;
            case "SM": return Application.SM;
            case "SXC": return Application.SXC;
            case "STC": return Application.STC;
            case "SXD": return Application.SXD;
            case "STD": return Application.STD;
            case "SXI": return Application.SXI;
            case "STI": return Application.STI;
            case "SXM": return Application.SXM;
            case "SXW": return Application.SXW;
            case "SXG": return Application.SXG;
            case "STW": return Application.STW;
            case "SUS": return Application.SUS;
            case "SVD": return Application.SVD;
            case "SIS": return Application.SIS;
            case "XSM": return Application.XSM;
            case "BDM": return Application.BDM;
            case "XDM": return Application.XDM;
            case "TAO": return Application.TAO;
            case "PCAP": return Application.PCAP;
            case "TMO": return Application.TMO;
            case "TPT": return Application.TPT;
            case "MXS": return Application.MXS;
            case "TRA": return Application.TRA;
            case "UFD": return Application.UFD;
            case "UTZ": return Application.UTZ;
            case "UMJ": return Application.UMJ;
            case "UNITYWEB": return Application.UNITYWEB;
            case "UOML": return Application.UOML;
            case "VCX": return Application.VCX;
            case "VSD": return Application.VSD;
            case "VIS": return Application.VIS;
            case "VSF": return Application.VSF;
            case "WBXML": return Application.WBXML;
            case "WMLC": return Application.WMLC;
            case "WMLSC": return Application.WMLSC;
            case "WTB": return Application.WTB;
            case "NBP": return Application.NBP;
            case "WPD": return Application.WPD;
            case "WQD": return Application.WQD;
            case "STF": return Application.STF;
            case "XAR": return Application.XAR;
            case "XFDL": return Application.XFDL;
            case "HVD": return Application.HVD;
            case "HVS": return Application.HVS;
            case "HVP": return Application.HVP;
            case "OSF": return Application.OSF;
            case "OSFPVG": return Application.OSFPVG;
            case "SAF": return Application.SAF;
            case "SPF": return Application.SPF;
            case "CMP": return Application.CMP;
            case "ZIR": return Application.ZIR;
            case "ZAZ": return Application.ZAZ;
            case "VXML": return Application.VXML;
            case "WGT": return Application.WGT;
            case "HLP": return Application.HLP;
            case "WSDL": return Application.WSDL;
            case "WSPOLICY": return Application.WSPOLICY;
            case "7Z": return Application._7Z;
            case "ABW": return Application.ABW;
            case "ACE": return Application.ACE;
            case "DMG": return Application.DMG;
            case "AAB": return Application.AAB;
            case "AAM": return Application.AAM;
            case "AAS": return Application.AAS;
            case "BCPIO": return Application.BCPIO;
            case "TORRENT": return Application.TORRENT;
            case "BLB": return Application.BLB;
            case "BZ": return Application.BZ;
            case "BZ2": return Application.BZ2;
            case "CBR": return Application.CBR;
            case "VCD": return Application.VCD;
            case "CFS": return Application.CFS;
            case "CHAT": return Application.CHAT;
            case "PGN": return Application.PGN;
            case "NSC": return Application.NSC;
            case "CPIO": return Application.CPIO;
            case "CSH": return Application.CSH;
            case "DEB": return Application.DEB;
            case "DGC": return Application.DGC;
            case "DIR": return Application.DIR;
            case "WAD": return Application.WAD;
            case "NCX": return Application.NCX;
            case "DTB": return Application.DTB;
            case "RES": return Application.RES;
            case "DVI": return Application.DVI;
            case "EVY": return Application.EVY;
            case "EVA": return Application.EVA;
            case "BDF": return Application.BDF;
            case "GSF": return Application.GSF;
            case "PSF": return Application.PSF;
            case "OTF": return Application.OTF;
            case "PCF": return Application.PCF;
            case "SNF": return Application.SNF;
            case "TTF": return Application.TTF;
            case "PFA": return Application.PFA;
            case "WOFF": return Application.WOFF;
            case "ARC": return Application.ARC;
            case "SPL": return Application.SPL;
            case "GCA": return Application.GCA;
            case "ULX": return Application.ULX;
            case "GNUMERIC": return Application.GNUMERIC;
            case "GRAMPS": return Application.GRAMPS;
            case "GTAR": return Application.GTAR;
            case "HDF": return Application.HDF;
            case "INSTALL": return Application.INSTALL;
            case "ISO": return Application.ISO;
            case "JNLP": return Application.JNLP;
            case "LATEX": return Application.LATEX;
            case "LZH": return Application.LZH;
            case "MIE": return Application.MIE;
            case "PRC": return Application.PRC;
            case "APPLICATION": return Application.APPLICATION;
            case "LNK": return Application.LNK;
            case "WMD": return Application.WMD;
            case "WMZ": return Application.WMZ;
            case "XBAP": return Application.XBAP;
            case "MDB": return Application.MDB;
            case "OBD": return Application.OBD;
            case "CRD": return Application.CRD;
            case "CLP": return Application.CLP;
            case "EXE": return Application.EXE;
            case "MVB": return Application.MVB;
            case "WMF": return Application.WMF;
            case "MNY": return Application.MNY;
            case "PUB": return Application.PUB;
            case "SCD": return Application.SCD;
            case "TRM": return Application.TRM;
            case "WRI": return Application.WRI;
            case "NC": return Application.NC;
            case "NZB": return Application.NZB;
            case "P12": return Application.P12;
            case "P7B": return Application.P7B;
            case "P7R": return Application.P7R;
            case "RAR": return Application.RAR;
            case "RIS": return Application.RIS;
            case "SH": return Application.SH;
            case "SHAR": return Application.SHAR;
            case "SWF": return Application.SWF;
            case "XAP": return Application.XAP;
            case "SQL": return Application.SQL;
            case "SIT": return Application.SIT;
            case "SITX": return Application.SITX;
            case "SRT": return Application.SRT;
            case "SV4CPIO": return Application.SV4CPIO;
            case "SV4CRC": return Application.SV4CRC;
            case "T3": return Application.T3;
            case "GAM": return Application.GAM;
            case "TAR": return Application.TAR;
            case "TCL": return Application.TCL;
            case "TEX": return Application.TEX;
            case "TFM": return Application.TFM;
            case "TEXINFO": return Application.TEXINFO;
            case "OBJ": return Application.OBJ;
            case "USTAR": return Application.USTAR;
            case "SRC": return Application.SRC;
            case "DER": return Application.DER;
            case "FIG": return Application.FIG;
            case "XLF": return Application.XLF;
            case "XPI": return Application.XPI;
            case "XZ": return Application.XZ;
            case "Z1": return Application.Z1;
            case "XAML": return Application.XAML;
            case "XDF": return Application.XDF;
            case "XENC": return Application.XENC;
            case "XHTML": return Application.XHTML;
            case "XML": return Application.XML;
            case "DTD": return Application.DTD;
            case "XOP": return Application.XOP;
            case "XPL": return Application.XPL;
            case "XSLT": return Application.XSLT;
            case "XSPF": return Application.XSPF;
            case "MXML": return Application.MXML;
            case "YANG": return Application.YANG;
            case "YIN": return Application.YIN;
            case "ZIP": return Application.ZIP;
            case "ADP": return Audio.ADP;
            case "AU": return Audio.AU;
            case "MID": return Audio.MID;
            case "MP4A": return Audio.MP4A;
            case "MP3" : return Audio.MP3;
            case "MPGA": return Audio.MPGA;
            case "OGA": return Audio.OGA;
            case "S3M": return Audio.S3M;
            case "SIL": return Audio.SIL;
            case "UVA": return Audio.UVA;
            case "EOL": return Audio.EOL;
            case "DRA": return Audio.DRA;
            case "DTS": return Audio.DTS;
            case "DTSHD": return Audio.DTSHD;
            case "LVP": return Audio.LVP;
            case "PYA": return Audio.PYA;
            case "ECELP4800": return Audio.ECELP4800;
            case "ECELP7470": return Audio.ECELP7470;
            case "ECELP9600": return Audio.ECELP9600;
            case "RIP": return Audio.RIP;
            case "WEBA": return Audio.WEBA;
            case "AAC": return Audio.AAC;
            case "AIF": return Audio.AIF;
            case "CAF": return Audio.CAF;
            case "FLAC": return Audio.FLAC;
            case "MKA": return Audio.MKA;
            case "M3U": return Audio.M3U;
            case "WAX": return Audio.WAX;
            case "WMA": return Audio.WMA;
            case "RAM": return Audio.RAM;
            case "RMP": return Audio.RMP;
            case "WAV": return Audio.WAV;
            case "XM": return Audio.XM;
            case "CDX": return Chemical.CDX;
            case "CIF": return Chemical.CIF;
            case "CMDF": return Chemical.CMDF;
            case "CML": return Chemical.CML;
            case "CSML": return Chemical.CSML;
            case "XYZ": return Chemical.XYZ;
            case "BMP": return Image.BMP;
            case "CGM": return Image.CGM;
            case "G3": return Image.G3;
            case "GIF": return Image.GIF;
            case "IEF": return Image.IEF;
            case "JPEG": return Image.JPEG;
            case "KTX": return Image.KTX;
            case "PNG": return Image.PNG;
            case "BTIF": return Image.BTIF;
            case "SGI": return Image.SGI;
            case "SVG": return Image.SVG;
            case "TIFF": return Image.TIFF;
            case "PSD": return Image.PSD;
            case "UVI": return Image.UVI;
            case "DJVU": return Image.DJVU;
            case "DWG": return Image.DWG;
            case "DXF": return Image.DXF;
            case "FBS": return Image.FBS;
            case "FPX": return Image.FPX;
            case "FST": return Image.FST;
            case "MMR": return Image.MMR;
            case "RLC": return Image.RLC;
            case "MDI": return Image.MDI;
            case "WDP": return Image.WDP;
            case "NPX": return Image.NPX;
            case "WBMP": return Image.WBMP;
            case "XIF": return Image.XIF;
            case "WEBP": return Image.WEBP;
            case "3DS": return Image._3DS;
            case "RAS": return Image.RAS;
            case "CMX": return Image.CMX;
            case "FH": return Image.FH;
            case "ICO": return Image.ICO;
            case "SID": return Image.SID;
            case "PCX": return Image.PCX;
            case "PIC": return Image.PIC;
            case "PNM": return Image.PNM;
            case "PBM": return Image.PBM;
            case "PGM": return Image.PGM;
            case "PPM": return Image.PPM;
            case "RGB": return Image.RGB;
            case "TGA": return Image.TGA;
            case "XBM": return Image.XBM;
            case "XPM": return Image.XPM;
            case "XWD": return Image.XWD;
            case "EML": return Message.EML;
            case "IGS": return Model.IGS;
            case "MSH": return Model.MSH;
            case "DAE": return Model.DAE;
            case "DWF": return Model.DWF;
            case "GDL": return Model.GDL;
            case "GTW": return Model.GTW;
            case "MTS": return Model.MTS;
            case "VTU": return Model.VTU;
            case "WRL": return Model.WRL;
            case "X3DB": return Model.X3DB;
            case "X3DV": return Model.X3DV;
            case "X3D": return Model.X3D;
            case "APPCACHE": return Text.APPCACHE;
            case "ICS": return Text.ICS;
            case "CSS": return Text.CSS;
            case "CSV": return Text.CSV;
            case "HTML": return Text.HTML;
            case "N3": return Text.N3;
            case "TXT": return Text.TXT;
            case "DSC": return Text.DSC;
            case "RTX": return Text.RTX;
            case "SGML": return Text.SGML;
            case "TSV": return Text.TSV;
            case "T": return Text.T;
            case "TTL": return Text.TTL;
            case "URI": return Text.URI;
            case "VCARD": return Text.VCARD;
            case "CURL": return Text.CURL;
            case "DCURL": return Text.DCURL;
            case "SCURL": return Text.SCURL;
            case "MCURL": return Text.MCURL;
            case "SUB": return Text.SUB;
            case "FLY": return Text.FLY;
            case "FLX": return Text.FLX;
            case "GV": return Text.GV;
            case "3DML": return Text._3DML;
            case "SPOT": return Text.SPOT;
            case "JAD": return Text.JAD;
            case "WML": return Text.WML;
            case "WMLS": return Text.WMLS;
            case "S": return Text.S;
            case "C": return Text.C;
            case "F": return Text.F;
            case "JAVA": return Text.JAVA;
            case "OPML": return Text.OPML;
            case "P": return Text.P;
            case "NFO": return Text.NFO;
            case "ETX": return Text.ETX;
            case "SFV": return Text.SFV;
            case "UU": return Text.UU;
            case "VCS": return Text.VCS;
            case "VCF": return Text.VCF;
            case "3GP": return Video._3GP;
            case "3G2": return Video._3G2;
            case "H261": return Video.H261;
            case "H263": return Video.H263;
            case "H264": return Video.H264;
            case "JPGV": return Video.JPGV;
            case "JPM": return Video.JPM;
            case "MJ2": return Video.MJ2;
            case "MP4": return Video.MP4;
            case "MPEG": return Video.MPEG;
            case "OGV": return Video.OGV;
            case "QT": return Video.QT;
            case "UVH": return Video.UVH;
            case "UVM": return Video.UVM;
            case "UVP": return Video.UVP;
            case "UVS": return Video.UVS;
            case "UVV": return Video.UVV;
            case "DVB": return Video.DVB;
            case "FVT": return Video.FVT;
            case "MXU": return Video.MXU;
            case "PYV": return Video.PYV;
            case "UVU": return Video.UVU;
            case "VIV": return Video.VIV;
            case "WEBM": return Video.WEBM;
            case "F4V": return Video.F4V;
            case "FLI": return Video.FLI;
            case "FLV": return Video.FLV;
            case "M4V": return Video.M4V;
            case "MKV": return Video.MKV;
            case "MNG": return Video.MNG;
            case "ASF": return Video.ASF;
            case "VOB": return Video.VOB;
            case "WM": return Video.WM;
            case "WMV": return Video.WMV;
            case "WMX": return Video.WMX;
            case "WVX": return Video.WVX;
            case "AVI": return Video.AVI;
            case "MOVIE": return Video.MOVIE;
            case "SMV": return Video.SMV;
            default: return Application.BIN;
        }

    }

//    public void generateFile(String in, String out) throws FileNotFoundException {
//        FileInputStream fis = new FileInputStream(in);
//        FileOutputStream fos = new FileOutputStream(out);
//        Scanner sc = new Scanner(fis);
//        PrintWriter pr = new PrintWriter(fos);
//
//        while (sc.hasNextLine()){
//            String s = sc.nextLine();
//            if (s.startsWith("#")){
//                continue;
//            }
//            s = s.replaceFirst("\t"," ").replace("\t","");
//            String[] split = s.split(" ");
//            pr.write("public static String "+split[1].toUpperCase()+" = \""+split[0]+"\";\n");
//            //System.out.println(split[0]+" --- "+split[1]);
//        }
//        pr.flush();
//        pr.close();
//    }
//
//    public void generateFromName(String in, String out) throws FileNotFoundException {
//        FileInputStream fis = new FileInputStream(in);
//        FileOutputStream fos = new FileOutputStream(out);
//        Scanner sc = new Scanner(fis);
//        PrintWriter pr = new PrintWriter(fos);
//
//        pr.write("switch(f) {");
//        while (sc.hasNextLine()){
//            String s = sc.nextLine();
//            if (s.startsWith("#")){
//                continue;
//            }
//            s = s.replaceFirst("\t"," ").replace("\t","");
//            String[] split = s.split(" ");
//            String n;
//            String t;
//            n = split[1];
//            t = split[0].split("/")[0];
//            t = Character.toUpperCase(t.charAt(0))+t.substring(1).toLowerCase();
//            pr.write("\tcase \""+n.toUpperCase()+"\": return "+t+"."+n.toUpperCase()+";\n");
//            //System.out.println(split[0]+" --- "+split[1]);
//        }
//        pr.write("}\n");
//        pr.flush();
//        pr.close();
//    }

    /* MimeTypes Generator
        try {
            MimeTypes mt = new MimeTypes();
            mt.generateFile("/home/blkr/mime.types","/home/blkr/mimes.java");
            mt.generateFromName("/home/blkr/mime.types","/home/blkr/mimes-func.java");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }*/
}
